### ISSUE TITLE
Python Script for Analyse Sales 

### ISSUE THREAD

**Issue by suyog44** [suyog44/github_tutorial#3]
#### Description
* Write a python script for analyse the sales from Kaggle dataset

#### Checklist
* Script is working fine,

**Comment by AkshayaKakde** [comment]
@suyog44 
### Added new files for sales data analysis:
- analyze_sales.py: Contains scripts for analyzing sales data.
- sales_data.csv: Raw sales data file.
- sales_data_analysis.ipynb: Jupyter notebook for detailed data analysis.
- README.md: Updated README file with project information.

**Comment by suyog44** [comment]
Thanks for completing in time. Approving MR #2.

Regards,                
Suyog
